let colours = ["#F29DB2","#ffd206","#ef3423","#1f4492","#0fa1d4","#048a35"]


const alphabet = {
  "default": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 5,
    "layout": 3,
    "size": 50,
    "lineColour": "#1f4492"
  },
  "A": {
    "offsetX": 0,
    "offsetY": 0,
    "numStations": 6,
    "layout": 1, // 1: circle, 2: line, 3: top curve, 4: bottom curve, 5: closed loop
    "connectionStyle" : 1,
    "size": 90,
    "customStationX": 45,
    "customStationY": 40,
    "customConnectionX": 45,
    "customConnectionY": 0,
    "lineColour": "#048a35"
  },
  "B": {
    "offsetX": 0,
    "offsetY": -5,
    "numStations": 8,
    "layout": 3,
    "size": 90,
    "customStationX": -45,
    "customStationY": -140,
    "customConnectionX": -45,
    "customConnectionY": 0,
    "lineColour": "#ef3423"
  },
  "C": {
    "offsetX": 0,
    "offsetY": -5,
    "numStations": 5,
    "layout": 1,
    "size": 90,
    "lineColour": "#0fa1d4"
  },
  "D": {
    "offsetX": 0,
    "offsetY": -5,
    "numStations": 8,
    "layout": 1,
    "size": 90,
    "customStationX": 45,
    "customStationY": -140,
    "customConnectionX": 45,
    "customConnectionY": 0,
    "lineColour": "#ef3423"
  },
  "E": {
    "offsetX": 0,
    "offsetY": -5,
    "numStations": 7,
    "layout": 1,
    "size": 90,
    "customStationX": -5,
    "customStationY": -5,
    "customConnectionX": 28,
    "customConnectionY": -35,
    "lineColour": "#048a35"
  },
  "F": {
    "offsetX": -25,
    "offsetY": -82,
    "customStationX": 50,
    "customStationY": -50,
    "customConnectionX": 0,
    "customConnectionY": 0,
    "numStations": 5,
    "size": 125,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#ffd206"
  },
  "G": {
    "offsetX": 0,
    "offsetY": -7,
    "numStations": 8,
    "layout": 1,              
    "size": 90,
    "customStationX": 10,
    "customStationY": 115,
    "customConnectionX": 45,
    "customConnectionY": 0,
    "lineColour": "#ef3423"
  },
  "H": {
    "offsetX": -30,
    "offsetY": -130,
    "customStationX": 70,
    "customStationY": 175,
    "customConnectionX": 0,
    "customConnectionY": 70,
    "numStations": 6,
    "size": 175,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#ffd206"
  },
  "I": {
    "offsetX": 0,
    "offsetY": -58,
    "numStations": 5,
    "size": 100,
    "customStationX": 0,
    "customStationY": -50,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#048a35"
  },
  "J": {
    "offsetX": 0,
    "offsetY": -50,
    "customStationX": -30,
    "customStationY": 160,
    "customConnectionX": 0,
    "customConnectionY": 125,
    "numStations": 5,
    "size": 125,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#0fa1d4"
  },
  "K": {
    "offsetX": -30,
    "offsetY": -130,
    "customStationX": 70,
    "customStationY": 0,
    "numStations": 6,
    "size": 175,
    "layout": 2,
    "lineAngle": 90,
    "customConnectionX": 0,
    "customConnectionY": 70,
    "lineColour": "#ef3423"
  },
  "L": {
    "offsetX": -20,
    "offsetY": -140,
    "numStations": 6,
    "customStationX": 35,
    "customStationY": 185,
    "customConnectionX": 0,
    "customConnectionY": 175,
    "connectionStyle": 3,
    "size": 175,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#1f4492"
  },
  "M": {
    "offsetX": -30,
    "offsetY": -30,
    "customStationX": -20,
    "customStationY": 75,
    "customConnectionX": 0,
    "customConnectionY": 0,
    "numStations": 4,
    "layout": 4,
    "size": 75,
    "lineColour": "#1f4492"
  },
  "N": {
    "offsetX": -45,
    "offsetY": -55,
    "customStationX": 75,
    "customStationY": 100,
    "customConnectionX": 0,
    "customConnectionY": 0,
    "numStations": 5,
    "size": 100,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#1f4492"
  },
  "O": {
    "offsetX": 0,
    "offsetY": 0,
    "numStations": 6,
    "layout": 3,
    "size": 90,
    "lineColour": "#048a35"
  },
  "P": {
    "offsetX": 0,
    "offsetY": -5,
    "numStations": 8,
    "layout": 3,
    "size": 90,
    "customStationX": -45,
    "customStationY": 140,
    "customConnectionX": -45,
    "customConnectionY": 0,
    "lineColour": "#ef3423"
  },
  "Q": {
    "offsetX": 0,
    "offsetY": -5,
    "numStations": 7,
    "layout": 1,
    "size": 90,
    "customStationX": 45,
    "customStationY": 140,
    "customConnectionX": 45,
    "customConnectionY": 0,
    "lineColour": "#0fa1d4"
  },
  "R": {
    "offsetX": -30,
    "offsetY": -55,
    "customStationX": 65,
    "customStationY": 0,
    "customConnectionX": 0,
    "customConnectionY": 25,
    "numStations": 5,
    "size": 100,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#1f4492"
  },
  "S": {
    "offsetX": -10,
    "offsetY": -30,
    "numStations": 3,
    "layout": 1,
    "size": 75,
    "customStationX": 0,
    "customStationY": 75,
    "customConnectionX": 38,
    "customConnectionY": 0,
    "lineColour": "#ffd206"
  },
  "T": {
    "offsetX": -10,
    "offsetY": -130,
    "numStations": 5,
    "size": 175,
    "customStationX": 50,
    "customStationY": 87,
    "customConnectionX": 0,
    "customConnectionY": 87,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#ef3423"
  },
  "U": {
    "offsetX": 45,
    "offsetY": -55,
    "customStationX": -75,
    "customStationY": 0,
    "customConnectionX": 0,
    "customConnectionY": 100,
    "connectionStyle": 1,
    "numStations": 5,
    "size": 100,
    "layout": 2,
    "lineAngle": 90,
    "lineColour": "#048a35"
  },
  "V": {
    "offsetX": -45,
    "offsetY": -50,
    "numStations": 4,
    "size": 100,
    "layout": 2,
    "customStationX": 85,
    "customStationY": 0,
    "customConnectionX": 42.5,
    "customConnectionY": 90.5,
    "connectionStyle": 1,
    "lineAngle": 65,
    "lineColour": "#ffd206"
  },
  "W": {
    "offsetX": -50,
    "offsetY": -30,
    "customStationX": 100,
    "customStationY": 0,
    "customConnectionX": 75,
    "customConnectionY": 75,
    "connectionStyle": 1,
    "numStations": 4,
    "layout": 4,
    "size": 75,
    "lineColour": "#1f4492"
  },
  "X": {
    "offsetX": -45,
    "offsetY": -45,
    "numStations": 5,
    "size": 125,
    "layout": 2,
    "customStationX": 85,
    "customStationY": 0,
    "customConnectionX": 15,
    "customConnectionY": 89,
    "lineAngle": 45,
    "lineColour": "#ffd206"
  },
  "Y": {
    "offsetX": -40,
    "offsetY": 125,
    "numStations": 5,
    "size": 185,
    "layout": 2,
    "customStationX": 0,
    "customStationY": -167,
    "customConnectionX": 40,
    "customConnectionY": -85,
    "connectionStyle": 1,
    "lineAngle": -65,
    "lineColour": "#048a35"
  },
  "Z": {
    "offsetX": -20,
    "offsetY": 40,
    "numStations": 4,
    "size": 100,
    "layout": 2,
    "customStationX": 0,
    "customStationY": -90,
    "customConnectionX": 42,
    "customConnectionY": -90,
    "lineAngle": -65,
    "lineColour": "#ffd206"
  },
  "0": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 0,
    "layout": 3,
    "size": 100,
    "lineColour": "#1f4492"
  },
  "1": {
    "offsetX": -50,
    "offsetY": -50,
    "numStations": 1,
    "size": 100,
    "layout": 1,
    "lineColour": "#ef3423"
  },
  "2": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 2,
    "size": 90,
    "layout": 1,
    "lineColour": "#ef3423"
  },
  "3": {
    "offsetX": -10,
    "offsetY": -50,
    "numStations": 3,
    "size": 90,
    "layout": 3,
    "lineColour": "#ffd206"
  },
  "4": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 4,
    "size": 90,
    "layout": 3,
    "lineColour": "#ffd206"
  },
  "5": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 5,
    "size": 90,
    "layout": 3,
    "lineColour": "#048a35"
  },
  "6": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 6,
    "size": 90,
    "layout": 3,
    "lineColour": "#048a35"
  },
  "7": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 7,
    "size": 90,
    "layout": 3,
    "lineColour": "#0fa1d4"
  },
  "8": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 8,
    "size": 90,
    "layout": 3,
    "lineColour": "#0fa1d4"
  },
  "9": {
    "offsetX": 0,
    "offsetY": -50,
    "numStations": 9,
    "size": 90,
    "layout": 3,
    "lineColour": "#1f4492"
  }

}